### PR TITLE
fix: extract image url for villager photoImage

### PR DESCRIPTION
**Pull request by cheng-kang**

### CODE REVIEW

**Comment by iamcal** [comment]
I added this in PR #9 which has now been open for over a month - i think this project is abandoned :(

**Comment by cheng-kang** [comment]
> I added this in PR #9 which has now been open for over a month - i think this project is abandoned :(

😞

**Comment by LavaToaster** [comment]
@iamcal Nah, not abandoned, just life!

I've merged your PR, closed this, regenerated the output, and published a new version of the package to npm.

**Comment by iamcal** [comment]
Thank you for maintaining!

I've just added #11 for the two new 1.6.0 sheets, sorry.

**Pull request closed without merging**
